apiVersion: apps/v1
kind: Deployment

metadata:
  name: ems-backend
  namespace: ems

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ems-backend

  template:
    metadata:
      labels:
        app: ems-backend

    spec:
      containers:
      - name: ems-backend

        image: YOUR_DOCKER_USER/ems-backend:v1

        imagePullPolicy: Always

        ports:
        - containerPort: 8080