apiVersion: apps/v1
kind: Deployment

metadata:
  name: ecommerce-backend
  namespace: ecommerce

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ecommerce-backend

  template:
    metadata:
      labels:
        app: ecommerce-backend

    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: ecommerce-backend

<<<<<<< HEAD
        image: rajvam6806/e-commerce-backend:b016d5ebfa8bb5a457b4bd6e34e202021367bdc9
=======
        image: rajvam6806/e-commerce-backend:v1
>>>>>>> 4982c8a8d3e119d4d0bc3a166a3a3db2d3b832c4

        imagePullPolicy: Always

        ports:
        - containerPort: 8080
