apiVersion: apps/v1
kind: Deployment

metadata:
  name: ecommerce-backend
  namespace: ecommerce

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ecommerce-backend

  template:
    metadata:
      labels:
        app: ecommerce-backend

    spec:
      imagePullSecrets:
        - name: dockerhub-secret

      containers:
        - name: ecommerce-backend

          image: rajvam6806/e-commerce-backend:be85df6dad3e0d1222409f19f6bc73c0e2e953eb

          imagePullPolicy: Always

          ports:
            - containerPort: 8080
