apiVersion: apps/v1
kind: Deployment

metadata:
  name: ecommerce-backend
  namespace: ecommerce

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ecommerce-backend

  template:
    metadata:
      labels:
        app: ecommerce-backend

    spec:
      imagePullSecrets:
        - name: dockerhub-secret

      containers:
        - name: ecommerce-backend

          image: rajvam6806/e-commerce-backend:b386efaf3efe6de90a0dd2aa5d6eecbd3e994074

          imagePullPolicy: Always

          ports:
            - containerPort: 8080
