apiVersion: apps/v1
kind: Deployment

metadata:
  name: ecommerce-frontend
  namespace: ecommerce

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ecommerce-frontend

  template:
    metadata:
      labels:
        app: ecommerce-frontend

    spec:
      containers:
      - name: ecommerce-frontend

        image: rajvam6806/e-commerce-frontend:2575d46199e26a1d09f90004ee64bca361d9fe3b

        imagePullPolicy: Always

        ports:
        - containerPort: 80

        env:
        - name: REACT_APP_API_URL
          value: aeb7e038165c449d789c27495443828d-753465246.ap-south-1.elb.amazonaws.com