apiVersion: apps/v1
kind: Deployment

metadata:
  name: ecommerce-frontend
  namespace: ecommerce

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ecommerce-frontend

  template:
    metadata:
      labels:
        app: ecommerce-frontend

    spec:
      containers:
        - name: ecommerce-frontend
          image: rajvam6806/e-commerce-frontend:042cadd949f18b34fac6922c9f797836b261052d

          imagePullPolicy: Always

          ports:
            - containerPort: 80

          env:
            - name: REACT_APP_API_URL
              value: "http://ecommerce-backend-service:8080"
