apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: ems
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/rajudruva2/eks-gitops-config
    targetRevision: main
    path: apps/ems

  destination:
    server: https://kubernetes.default.svc
    namespace: ems

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
