apiVersion: v1
kind: ConfigMap

metadata:
  name: backstage-config
  namespace: backstage

data:
  app-config.yaml: |
    app:
      title: Raj Platform
      baseUrl: https://backstage.rajplatform.online

    organization:
      name: Raj Platform

    backend:
      baseUrl: https://backstage.rajplatform.online

      listen:
        host: 0.0.0.0
        port: 7007

      cors:
        origin: https://backstage.rajplatform.online
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true

      auth:
        dangerouslyDisableDefaultAuthPolicy: true

      database:
        client: better-sqlite3
        connection: ':memory:'

    auth:
      environment: development

      providers:
        guest: {}

    scaffolder: {}

    techdocs:
      builder: local

      generator:
        runIn: docker

      publisher:
        type: local

    catalog:
      rules:
        - allow:
            - Component
            - System
            - API
            - Resource
            - Location
            - Template

      locations:
        - type: url
          target: https://raw.githubusercontent.com/rajudruva2/backstage-catalog/main/catalog-info.yaml

    kubernetes: {}

    permission:
      enabled: false
