
apiVersion: v1
kind: ConfigMap

metadata:
  name: backstage-config
  namespace: backstage

data:
  app-config.yaml: |
    app:
      title: Backstage
      baseUrl: "https://backstage.rajplatform.online"

    organization:
      name: Raj Platform

    backend:
      auth:
        keys:
          - secret: development

      baseUrl: "https://backstage.rajplatform.online"

      listen:
        host: 0.0.0.0
        port: 7007

      cors:
        origin: "https://backstage.rajplatform.online"
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true

    database:
      client: pg

      connection:
        connectionString: postgresql://backstage:backstage123@postgres.postgres.svc.cluster.local:5432/backstage

    auth:
      environment: production

      providers:
        github:
          production:
            clientId: Iv23livROY8boMO2XoTk
            clientSecret: cb5e5a1c931e99a7df4940e924ae675ec54bd51c

    scaffolder: {}

    techdocs:
      builder: local

      generator:
        runIn: docker

      publisher:
        type: local

    catalog:
      rules:
        - allow: [Component, System, API, Resource, Location]

    integrations:
      github:
        - host: github.com
