apiVersion: v1
kind: ConfigMap

metadata:
  name: backstage-config
  namespace: backstage

data:
  app-config.yaml: |
    app:
      title: Raj Platform
      baseUrl: https://backstage.rajplatform.online

    organization:
      name: Raj Platform

    backend:
      baseUrl: https://backstage.rajplatform.online

      listen:
        host: 0.0.0.0
        port: 7007

      cors:
        origin: https://backstage.rajplatform.online
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true

      auth:
        keys:
          - secret: backstage-secret-key

      database:
        client: better-sqlite3
        connection: ':memory:'

    integrations:
      github:
        - host: github.com

    auth:
      environment: production

      providers:
        github:
          production:
            clientId: YOUR_GITHUB_CLIENT_ID
            clientSecret: YOUR_GITHUB_CLIENT_SECRET

    scaffolder: {}

    techdocs:
      builder: local

      generator:
        runIn: docker

      publisher:
        type: local

    catalog:
      rules:
        - allow: [Component, System, API, Resource, Location]
