apiVersion: apps/v1
kind: Deployment

metadata:
  name: backstage
  namespace: backstage

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backstage

  strategy:
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: backstage

    spec:
      containers:
        - name: backstage

          image: rajvam6806/backstage-platform:7be3811847aaf048b4f20d958bc91fe849899643

          imagePullPolicy: Always

          command:
            - node

          args:
            - packages/backend
            - --config
            - /app/app-config.yaml

          ports:
            - containerPort: 7007

          env:
            - name: NODE_ENV
              value: production
          envFrom:
          - secretRef:
              name: githubauthids    

          volumeMounts:
            - name: backstage-config-volume
              mountPath: /app/app-config.yaml
              subPath: app-config.yaml

          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 7007
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 7007
            initialDelaySeconds: 60
            periodSeconds: 20

          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"

            limits:
              cpu: "1"
              memory: "2Gi"

      volumes:
        - name: backstage-config-volume
          configMap:
            name: backstage-config
