apiVersion: apps/v1
kind: Deployment

metadata:
  name: backstage
  namespace: backstage

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backstage

  template:
    metadata:
      labels:
        app: backstage

    spec:
      containers:
      - name: backstage

        image: rajvam6806/backstage:31c704434e93dbc854b4cf730465346887f6cc28

        imagePullPolicy: Always

        ports:
        - containerPort: 7007

        envFrom:
        - secretRef:
            name: backstage-secret
        - secretRef:
            name: backstage-github-auth    

        volumeMounts:
        - name: backstage-config
          mountPath: /app/app-config.production.yaml
          subPath: app-config.production.yaml

        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 7007

        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 7007

      volumes:
      - name: backstage-config
        configMap:
          name: backstage-config
