apiVersion: apps/v1
kind: Deployment

metadata:
  name: backstage
  namespace: backstage

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backstage

  template:
    metadata:
      labels:
        app: backstage

    spec:
      containers:
        - name: backstage

          image: rajvam6806/backstage:c686919621f8a6b276a2843713010414e0f9fd9e

          ports:
            - containerPort: 7007

          env:
            - name: NODE_ENV
              value: production
          envFrom:
            - secretRef:
                name: backstage-secret

            - secretRef:
                name: backstage-github-auth    
