apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
spec:
  ports:
  - nodePort: 32208
    port: 80
    targetPort: 7007
  selector:
    app: backstage
  type: ClusterIP
